# User config
author: "Karlo NFT"
tagline: "I like to draw stuff."
description: "Yo! My name is Karlo and I am 7 years old. My Dad set this website up for me and gave me 1 ERG to get started. The journey begins now."
keywords: "Karlo NFT, Ergo NFT, College Fund"
twitter: "https://twitter.com/"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
