# User config
author: "Karlo NFT"
tagline: "I like to draw stuff."
description: "Yo! My name is Karlo and I am 7 years old. My Dad set up this website and gave me 1 ERG to get started. If you like my drawings, I will make more..
keywords: "Karlo NFT, Ergo NFT, College Fund"
twitter: "https://twitter.com/"
email: "9i1bWsPbJgSX3V2Nc64kLTFVEudfx3wQD6Xv9WFyJTEgvw8ELFk"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
