# User config
author: "Karlo NFT"
tagline: "I like to draw stuff."
description: "Yo! My name is Karlo and I am 6 years old. I like to draw stuff. My Dad set this up for me. My keys - my coins."
keywords: "Karlo NFT, Ergo NFT, College Fund"
email: "KarloNFT@outlook.com"
twitter: "https://twitter.com/"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
