# User config
author: "Karlo NFT"
tagline: "I like to draw stuff."
description: "Yo! My name is Karlo and I am 7 years old. My Dad set this website up for me and helped me to get started. If you like my drawings, I will make more. Mint address is: 9i1bWsPbJgSX3V2Nc64kLTFVEudfx3wQD6Xv9WFyJTEgvw8ELFk"
keywords: "Karlo NFT, Ergo NFT, College Fund"
twitter: "https://twitter.com/"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
